[project]
name = "proj-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.11.10",
    "lxml-html-clean>=0.4.1",
    "pandas>=2.2.3",
    "requests-html>=0.10.0",
    "typing-extensions>=4.12.2",
]
