name: run cicd

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: 

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update

      - name: Install Python dependencies
        run: |
          pip install uv
          uv venv
          uv pip install requests-html aiohttp

      - name: Run extract_urls.py
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          AUTHKEY: ${{ secrets.AUTHKEY }}
        run: uv run extract_urls.py


      - name: Commit and push files
        env:
          GITHUB_ACTIONS_BOT_TOKEN: ${{ secrets.GITHUB_ACTIONS_BOT_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "update files" -a
        
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_ACTIONS_BOT_TOKEN: ${{ secrets.GITHUB_ACTIONS_BOT_TOKEN }}
          branch: main  
